fix erreurs sentry wip
anct-cnum/dashboard pull request #205
Opened 2023-07-28 15:26 UTC by dienamo

https://sentry.incubateur.net/organizations/betagouv/issues/56034/?project=58
https://sentry.incubateur.net/organizations/betagouv/issues/56021/?project=58

2023-07-28 15:44 UTC, QuentinFontenay approved these changes

2023-07-31 08:40 UTC, squirrion commented on src/components/StructureContactForm.js
> +      dispatch(structureActions.updateStructureEmail(infoForm?.email.trim(), structure?._id));
```suggestion
      dispatch(structureActions.updateStructureEmail(infoForm?.email?.trim(), structure?._id));
```

2023-07-31 08:41 UTC, squirrion commented on src/views/connected/structure/Exports.js
> +          <p>Une erreur est survenue : {error?.message?.toString()}</p>
Faudrait voir ici ce que contient error : est-ce qu'ici le message serait directemen au niveau de error ?

2023-08-01 13:35 UTC, squirrion requested changes
error?.message?.toString() => il est possible que le message soit au niveau de error directement sans le .message => à tester

2023-08-01 14:42 UTC, squirrion approved these changes

2023-08-01 14:45 UTC, merged