detail d'un conseiller en fin de contrat naturel
anct-cnum/dashboard pull request #335
Opened 2023-11-30 12:10 UTC by QuentinFontenay

2023-11-30 13:33 UTC, MorganP-projects commented on src/components/AccordeonContrats.js
> +function AccordeonContrats({ misesEnRelationNouvelleRupture, misesEnRelationFinaliseeRupture, misesEnRelationFinalisee, misesEnRelationTermineeNaturel, conseiller }) {
misesEnRelationTermineeNaturelle (partout du coup :) )

2023-11-30 13:36 UTC, MorganP-projects commented on src/components/cards/ContratsCards.js
> +                        Non reconduction du con...
peut-être rajouté quelques lettre à la fin :p

2023-11-30 13:37 UTC, MorganP-projects commented on src/views/connected/admin/conseillers/ConseillerDetails.js
> +        setMisesEnRelationTermineeNaturel(conseiller.misesEnRelation?.filter(miseEnRelation => miseEnRelation.statut === 'terminee_naturel'));
terminee_naturelle

2023-12-05 09:36 UTC, squirrion commented on src/components/cards/ContratsCards.js
> +            className={`fr-card fr-col-12 fr-p-4w contrat-terminer ${misesEnRelationFinalisee?.length > 0 || misesEnRelationNouvelleRupture || misesEnRelationFinaliseeRupture?.length > 0 ? 'fr-mt-3w'
oula compliqué non ?

2023-12-05 09:38 UTC, squirrion commented on src/components/cards/ContratsCards.js
> +                        Non-reconduction
Pas le même motif que dans le fichier précédent normal ? (il y avait "du contrat" dans l'autre)

2023-12-05 09:39 UTC, squirrion commented on src/views/connected/admin/conseillers/ConseillerDetails.js
> -        if (conseiller?.statut !== 'RUPTURE') {
normal ?

2023-12-05 09:40 UTC, squirrion commented on src/views/connected/admin/conseillers/ConseillerDetails.js
> +      {conseiller?.structureId &&
normal ce changement, c'est moins explicite

2023-12-05 09:40 UTC, squirrion commented on src/views/connected/admin/contrats/ConseillerDetailsContrat.js
> +        if (conseiller?.structureId) {
idem moins explicite

2023-12-05 09:40 UTC, squirrion commented on src/views/connected/admin/contrats/ConseillerDetailsContrat.js
> +      {conseiller?.structureId &&
idem

2023-12-05 09:41 UTC, squirrion commented on src/views/connected/admin/contrats/ConseillerDetailsContrat.js
> +      {conseiller?.structureId &&
ca complexifie trop, on a des if sur du statut et du if sur du structureId

2023-12-05 09:41 UTC, squirrion commented on src/views/connected/grandReseau/conseillers/ConseillerDetails.js
> +      {conseiller?.structureId &&
Idem

2023-12-06 16:35 UTC, QuentinFontenay commented on src/components/cards/ContratsCards.js
> +                        Non-reconduction
dans l'autre c'est la version responsive, il y a plus de place pour afficher le texte en entier. J'en ai parlé avec Lauren elle est ok pour mettre "Non-reconduction" ce qui permet d'afficher sur une seule ligne

2023-12-07 10:17 UTC, squirrion commented on src/components/cards/ContratsCards.js
> +                            `${miseEnRelation?.motifRupture.substring(0, 27)}...` : formatMotifRupture(miseEnRelation?.motifRupture)
idem à voir pour le trunc avec le CSS

2023-12-07 10:19 UTC, squirrion commented on src/views/connected/admin/conseillers/ConseillerDetails.js
> +      {conseiller?.structureId &&
il faudrait laisser les checks comme avant

2023-12-07 10:20 UTC, squirrion commented on src/views/connected/admin/contrats/ConseillerDetailsContrat.js
> +        if (conseiller?.structureId) {
pas compris : équivalement à RECRUTE || TERMINE

2023-12-11 20:08 UTC, squirrion commented on src/components/AccordeonContrats.js
> +function AccordeonContrats({ misesEnRelationNouvelleRupture, misesEnRelationSansMission, misesEnRelationFinalisee, conseiller }) {
normal ?

2023-12-11 20:10 UTC, squirrion commented on src/components/AccordeonContrats.js
> +                          </span> : <span>-</span>
pas de non reconduction du contrat par défaut comme sur l'autre vue plus bas dans la PR ?

2023-12-14 13:52 UTC, Ornella452 approved these changes

2023-12-18 09:47 UTC, squirrion approved these changes

2023-12-29 21:59 UTC, squirrion commented
Faudra qu'on voit aussi ici pour un rebase ca va être un historique de commit trop invasif

2024-01-02 15:16 UTC, squirrion commented
A voir aussi suite à la refacto checkIsConseiller si impact ou pas ?

2024-01-09 16:35 UTC, squirrion commented on src/views/connected/coordinateur/conseillers/ConseillerDetails.js
> +          {(conseiller?.statut === 'RUPTURE' || conseiller?.statut === 'TERMINE') &&
@QuentinFontenay voir car une fonction checkIsConseiller avait été mise dans une autre PR je crois à voir où ca impacterait

2024-01-11 12:48 UTC, squirrion requested changes
Il faut faire un merge staging et voir si besoin de refacto

2024-01-11 18:56 UTC, Ornella452 approved these changes

2024-01-17 10:53 UTC, closed without merging