Mettre le salaire en varialble d'environnement
anct-cnum/dashboard pull request #365
Opened 2023-12-18 15:12 UTC by MorganP-projects

2023-12-18 15:55 UTC, squirrion commented on src/views/connected/structure/popins/PopinEditionContrat.js
> +  const salaireMinimum = Number(process.env.REACT_APP_CONTRAT_SMIC);
côté front, quand on valide et que la saisie est inférieure au SMIC côté admin et structure, du coup la modale se bloque bien avec l'erreur ? (se ferme pas)

2023-12-19 08:48 UTC, MorganP-projects commented on src/views/connected/structure/popins/PopinEditionContrat.js
> +  const salaireMinimum = Number(process.env.REACT_APP_CONTRAT_SMIC);
On ne peut pas validé. Le bouton est grisé et l'erreur est affiché tant que l'on est inférieur au SMIC.

2023-12-19 10:34 UTC, squirrion commented
@QuentinFontenay du coup la refacto est à faire côté front en décomposant structure & admin ?

2023-12-19 13:52 UTC, Ornella452 approved these changes

2023-12-21 14:52 UTC, QuentinFontenay requested changes
MEP

2023-12-22 08:49 UTC, QuentinFontenay approved these changes

2023-12-22 09:01 UTC, merged