Nouveau filtre sur les stats conseiller: filtrer par structure
anct-cnum/dashboard pull request #381
Opened 2023-12-28 16:56 UTC by QuentinFontenay

2023-12-29 21:57 UTC, squirrion commented on src/components/conseillers/StatsConseiller.js
> +          {listeStructures?.length > 1 ?
PDF OK ?

2023-12-29 21:57 UTC, squirrion commented on src/utils/formatagesUtils.js
> +  return `Statistiques_${removeCodePrefix(type)}${codePostal ? `_${codePostal}` : ''}${ville ? `_${ville}` : ''}_${formatDate(dateDebut)}_${formatDate(dateFin)}`;
normal ?

2024-01-02 08:44 UTC, QuentinFontenay commented on src/components/conseillers/StatsConseiller.js
> +          {listeStructures?.length > 1 ?
oui

2024-01-02 09:52 UTC, squirrion commented on src/utils/formatagesUtils.js
> +  return `Statistiques_${removeCodePrefix(type)}${codePostal ? `_${codePostal}` : ''}${ville ? `_${ville}` : ''}_${formatDate(dateDebut)}_${formatDate(dateFin)}`;
Le remplacer peut etre par prenom - nom avec un petit slugify

2024-01-02 15:21 UTC, squirrion commented on src/actions/statistiquesActions.js
> +function getStatistiquesConseiller(dateDebut, dateFin, idConseiller, codePostal = null, codeCommune = null, idStructure) {
pas besoin de le force à null comme le codePostal qui correspondrait à toutes ?

2024-01-02 15:22 UTC, squirrion commented on src/utils/formatagesUtils.js
> +  return `Statistiques_${removeCodePrefix(type)}${formatNomConseillerExport(nom, prenom)}${codePostal ? `_${codePostal}` : ''}${ville ? `_${ville}` : ''}_${formatDate(dateDebut)}_${formatDate(dateFin
je vois qu'on a le code postal si présent,  à faire pour la structure avec le nom ?

2024-01-03 08:08 UTC, QuentinFontenay commented on src/actions/statistiquesActions.js
> +function getStatistiquesConseiller(dateDebut, dateFin, idConseiller, codePostal = null, codeCommune = null, idStructure) {
non pas besoin car le state par défaut est un array vide

2024-01-04 16:44 UTC, squirrion commented on src/reducers/statistiquesReducer.js
> +        error: true,
action.error du coup vu que tu le récupères. Message sera bien prévue en affichage ?

2024-01-04 16:46 UTC, squirrion commented on src/services/statistiquesService.js
> +  return API.get(`${apiUrlRoot}/cras/filtres/conseiller?role=${roleActivated()}&id=${idConseiller}`)
niveau access control pas de soucis si structure A consulte les stats de son conseiller mais de structure B

2024-01-04 16:49 UTC, squirrion commented on src/views/connected/commun/statistiques/Components/graphiques/StatistiquesBanniere.js
> +          const nomStructure = listeStructures?.find(structure => structure?.structureId === structureIds[0])?.nom;
comparaison en string ?

2024-01-05 09:55 UTC, QuentinFontenay commented on src/services/statistiquesService.js
> +  return API.get(`${apiUrlRoot}/cras/filtres/conseiller?role=${roleActivated()}&id=${idConseiller}`)
la structure peut pas avoir accès aux stats des CRA sur les anciennes structures du conseiller apart lors du recrutement

2024-01-05 09:59 UTC, QuentinFontenay commented on src/views/connected/commun/statistiques/Components/graphiques/StatistiquesBanniere.js
> +          const nomStructure = listeStructures?.find(structure => structure?.structureId === structureIds[0])?.nom;
côté front il y a pas besoin car c'est des string pas des oid

2024-01-11 12:54 UTC, squirrion commented on src/views/connected/commun/statistiques/Components/graphiques/StatistiquesBanniere.js
> +/* eslint-disable max-len */
normal ?

2024-01-11 12:55 UTC, squirrion commented on src/views/connected/commun/statistiques/Components/graphiques/StatistiquesBanniere.js
> +        default:
ok on a pas un case spé qu'on pourrait mettre pour bien le cibler ?

2024-01-11 12:56 UTC, squirrion commented on src/components/conseillers/StatsConseiller.js
> +                defaultValue={''}
c'est pas tous ?

2024-01-11 12:56 UTC, squirrion requested changes
A confirmer si on se base sur staging ou recette

2024-01-11 19:12 UTC, Ornella452 commented on src/views/connected/commun/statistiques/Components/graphiques/StatistiquesBanniere.js
> +          dispatch(exportsActions.exportStatistiquesConseillerCSV(dateDebut, dateFin, id, codePostal, ville, codeCommune, nom, prenom, structureIds, nomStructure));
`id` => `idType`

2024-01-16 09:01 UTC, squirrion approved these changes

2024-01-17 08:43 UTC, merged